[package]
name = "galaxy_simulation"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
ratatui = "0.29"
crossterm = "0.29"
rand = "0.9.2"
rayon = "1.11.0"